### ISSUE TITLE
Zusammenspiel mit hyphenator

### ISSUE THREAD

**Issue by DanielWeitenauer** [iceman-fx/seocheckup#10]
Hi, wenn das Addon hyphenator verwendet wird, funktioniert der Vergleich der Worte mit Seitentitel und Überschriften nicht mehr zuverlässig, wenn die Texte das Steuerzeichen &shy; nicht gleichermaßen beinhalten.  
Müssen die Texte vor dem Vergleich bereinigt werden?

**Comment by iceman-fx** [comment]
Was macht denn eigentlich Hyphenator mit dem Text?

**Comment by DanielWeitenauer** [comment]
Er fügt Silbentrennungen in den Text ein. Dafür wird das bedingte Trennzeichen &shy; benutzt. 
Das müsste dann vor den Vergleichen aus den Texten gefiltert werden.

**Comment by iceman-fx** [comment]
Ist eine Silbentrennung aus SEO-Sicht überhaupt sinnvoll?
Versteht das denn Google und Co?

**Comment by iceman-fx** [comment]
Das Problem beim rausfiltern kann sein, dass damit auch erwünschte Such-Kombinationen verloren gehen.

**Comment by DanielWeitenauer** [comment]
Mir fällt kein Grund ein, warum ein Text mit Softhyphens erwünscht anders bewertet werden sollte als einer ohne, da es sich ja nur um ein Zeichen mit vorschlagendem Character handelt, das je nach Ausgabe sichtbar in Erscheinung tritt oder eben nicht. Selbst ohne Hyphenator könnte es vorkommen, dass die Redaktion den Softhyphen im Text einfügt, in einer Headline jedoch nicht.
Zumindest Google schien bereits vor 10 Jahren kein Problem mit dem Softhyphen zu haben: https://www.gurkcity.de/blog/Google-und-die-shy-Entity-55.html

**Comment by iceman-fx** [comment]
Ich verstehe das Addon Hyphenator nicht.
Das macht bei mir rein gar nix. Der Text sieht in der Ausgabe immer noch aus wie vorher.

Aber auch wenn es etwas machen würde, nach welchem Kriterium trennt es denn das Wort?
Woher will denn das Addon wissen, wie breit die Darstellungsfläche ist und wann es dann bei welcher Auflösung trennen muss?

**Comment by iceman-fx** [comment]
OK, ich verstehe das Addon und dessen Ausgabe immer noch nicht, aber mit dem nächsten Release kommt eine Anbindung an das Hyphenator-Addon.
