### ISSUE TITLE
WDF IDF anstelle von Keyworddichte

### ISSUE THREAD

**Issue by rkemmere** [iceman-fx/seocheckup#11]
Hey, wie sieht es aus. Kann man das Addon so erweitern, dass die WDF IDF Berechnung anstelle der Keyworddichte zu Grunde gelegt wird?

Viele Grüße
Ronny

**Comment by iceman-fx** [comment]
Hast Du dazu auf die eine Berechnungsgrundlage?

**Comment by rkemmere** [comment]
https://de.ryte.com/wiki/WDF*IDF

Natürlich für das einzelne Wort. Ggf. kann man das auch so bauen, das ein kleiner Graph eingebaut ist. 

Kann man ja anstelle der Keyworddichte anzeigen lassen. 
Stopwörter sollten dann noch pflegbar gemacht werden.

**Comment by iceman-fx** [comment]
Kannst du bitte deinen Programmcode zur Berechnung bereitstellen?
