### ISSUE TITLE
Undefined index functions_be_seo.inc.php 1725

### ISSUE THREAD

**Issue by bepixeld** [iceman-fx/seocheckup#21]
Das Array Feld $wc_token[$word] wird nicht initialisiert. Deshalb wird für jedes neues Wort eine notice im Log geschrieben.
Notice undefined index in redaxo/src/addons/seocheckup/functions/functions_be_seo.inc.php 1725
Das Problem kann mit Pull request #20 verhindert werden. Ich hoffe das hilft weiter.

**Comment by iceman-fx** [comment]
in der 1.4.6 gefixt

Danke.
