### ISSUE TITLE
Uncaught DOMException nach Modul speichern

### ISSUE THREAD

**Issue by marcohanke** [iceman-fx/seocheckup#23]
Moin, wenn ich ein Modul speichere (egal welches) bekomme ich in der Konsole:
Uncaught DOMException: Document.querySelector: ‘#slice-add-pos-1&seocucnt=changed&seocucnt=changed’ is not a valid selector
Und der Spinner hört nicht auf zu spinnen ;-)

**Comment by iceman-fx** [comment]
Hast du die aktuellste Version installiert, bei der dies behoben sein sollte?

**Comment by marcohanke** [comment]
Arghhhh, ich hatte es direkt vor'm Release installiert ;-)
Sorry und danke.
