### ISSUE TITLE
Anzeige: Worte aus dem Seitentitel fehlen im Content 

### ISSUE THREAD

**Issue by thorol** [iceman-fx/seocheckup#24]
Die Worte aus dem Seitentitel werden nur in den Überschriften gesucht, nicht generell im Content. 

https://github.com/iceman-fx/seocheckup/blob/a6b7f796ab4661b26a47c27fad73e6f53a994c89/functions/functions_be_seo.inc.php#L654

**Comment by iceman-fx** [comment]
Das ist so schon korrekt.
Es wird im Content gesucht, welcher aber nicht die H1 enthält.

$artcnt_wo_h1 = preg_replace("/<h1[^>]*>.*?<\/h1>/is", "", $artcnt_raw);

**Comment by thorol** [comment]
Ok, da stand ich auf dem Schlauch, alles in Ordnung. Danke!
