### ISSUE TITLE
Url V2 generierte Links können nur über http abgefragt werden.

### ISSUE THREAD

**Issue by thorol** [iceman-fx/seocheckup#25]
Die URLs des URL Addon können nur über http und nicht über https aufgerufen werden. Dadurch generiert der Check einen Weiterleitungsfehler. 
Wie auch bei der Prüfung der Redaxo-Artikel könnte der folgende Schnippsel eingebaut werden. Es würde wenigstens für yrewrite-Nutzer Abhilfe schaffen. 
https://github.com/iceman-fx/seocheckup/blob/a6b7f796ab4661b26a47c27fad73e6f53a994c89/pages/ajax.load-urllist.inc.php#L81
`
if (rex_addon::get('yrewrite')->isAvailable()):
	$prot = (rex_yrewrite::isHttps()) ? 'https://' : $prot;
endif;
`

**Comment by iceman-fx** [comment]
Das ist nun in der aktuellen Version gefixt.

**Comment by thorol** [comment]
Passt, danke.
