### ISSUE TITLE
AddOn-Key mit FOR verknüpfen

### ISSUE THREAD

**Issue by schuer** [iceman-fx/seocheckup#4]
Der AddOn-Key sollte mit Friends Of REDAXO verknüpft sein und ist aktuell aber mit manetage verknüpft. Jemand vom Core-Team kann ihn neu zuweisen.

https://redaxo.org/download/addons/seocheckup/

(API-Key von FOR kann im Slack erfragt werden. Zum Publizieren neuer Releases.)

**Comment by tbaddade** [comment]
> Der AddOn-Key sollte mit Friends Of REDAXO verknüpft sein

ist erledigt

**Comment by schuer** [comment]
Danke, Thomas!

Falko hat sich nun allerdings entschieden, seine beiden AddOns `seocheckup` und `be_tools` doch lieber selbst unter seinem Namen zu entwickeln, nicht bei FOR. Dass sie überhaupt bei FOR gelandet sind, war ein kleines Missverständnis, deshalb ist es okay, wenn er sie nun wieder raus zieht.
Gregor hat bereits die AddOn-Keys verschoben. Die Repos verschiebt Falko in Kürze selbst, uns anderen fehlen dafür die Schreibrechte in seinem Account.

Ich schließe hier.
