### ISSUE TITLE
SERP-Vorschau an neuestes Google Layout anpassen

### ISSUE THREAD

**Issue by bitshiftersgmbh** [iceman-fx/seocheckup#5]
Google hatte vor kurzem das Layout & Design seiner SERPs angepasst.
Insofern ist die Vorschau am Artikel (mit dem grünen Text) nicht mehr aktuell.

Ob es Anpassungen bei den Zeichenlängen für title und description gab, konnte ich auf die Schnelle nicht herausfinden.

**Comment by iceman-fx** [comment]
Ist vermerkt, ich warte aber noch etwas damit - vielleicht ändert Google ja noch etwas.
