### ISSUE TITLE
/* */ Kommentarzeichen unter SERP-Preview

### ISSUE THREAD

**Issue by bitshiftersgmbh** [iceman-fx/seocheckup#6]
Im SERP-Snippet direkt am Artikel (rechte Spalte) ist darunter immer ein `/* */` zu sehen. Sieht aus wie eine nicht komplett eliminierte alte Debug-Ausgabe. Könnte man mal entfernen bei Gelegenheit. :)

**Comment by iceman-fx** [comment]
Ja, ist bekannt und wird beim nächsten Update entfernt ;-)
