### ISSUE TITLE
Wunsch: Kopplung an Url-AddOn

### ISSUE THREAD

**Issue by bitshiftersgmbh** [iceman-fx/seocheckup#7]
Das AddOn läuft für normale Artikel sehr gut. Zur Komplettierung des Inhaltes einer Homepage müssten aus meiner Sicht aber noch die durch das Url-AddOn erzeugten Seiten inkludiert werden.

Bei installiertem und aktiviertem Url-AddOn fände ich ein 2. Tab rechts neben "Artikel-CheckUp" toll, dass dann "Url-AddOn-CheckUp" oder irgendwie so heißen könnte. Dort gibt es dann - analog zu den etwaigen Sprachen beim Artikel-CheckUp - ein Untermenü mit allen aktiven Url-AddOn Sets.

Ich hab keine Ahnung wie das System arbeitet (wird die Frontend-Ausgabe geparst?). Es sieht mir aber so aus, als könnte der Rest der Anpassungen technisch recht schnell integrierbar sein (?)

**Comment by iceman-fx** [comment]
Ja, die Frontend-Seite wird geparst, da die Backenddaten nicht immer korrekt sind und auch nicht den IST-Zustand wiederspiegeln.

Das URL-Addon erzeugt doch sprechende URLs für Datenbankparameter (events.html?id=1) - richtig?
Diese "virtuellen Seiten" haben dann aber doch immer noch alle die gleichen Werte für die wichtigsten SEO-Parameter (z.B. title, description etc.), wodurch der Check keine wirklich sinnvollen Ergebnisse liefern würde.

**Comment by bitshiftersgmbh** [comment]
Naja, das stimmt nur bedingt. Ja, das Url-AddOn bietet dafür Felder an. Ich habe aber gelegentlich Fälle, in denen ich dafür über spezielle Felder und Weichen Sonderlösungen anbiete.

Auch für ALT-Fehler bei Bildern oder Überschriften-Prüfung wäre das sinnvoll. Wir haben auf Kundenseiten zuweilen doch komplexere Pages, die aus YForm Tables via Url-AddOn bereitgestellt werden.

**Bsp.:** 
https://www.zobjack.de/angebote/astra-sports-tourer-14t-active-klimaautomatik-927
https://www.zobjack.de/ihr-autohaus/aktuelles/der-neue-opel-corsa-premierenfeier-am-16-november#read

**Comment by tbaddade** [comment]
> Diese "virtuellen Seiten" haben dann aber doch immer noch alle die gleichen Werte für die wichtigsten SEO-Parameter (z.B. title, description etc.)

Nein. Diese Felder können von Datensatz zu Datensatz unterschiedlich sein.

**Comment by iceman-fx** [comment]
Verständnisfrage:
Das URL Addon spielt eigene werte für title + desc in die yrewrite SEO Ausgabe ein?
Woher nimmt es denn diese Werte?

@bitshiftersgmbh bitte erkläre mir mal an deinem zobjack Beispiel, woher du die Daten für die SEO Angaben ziehst.
Danke.

**Comment by bitshiftersgmbh** [comment]
![Unbenannt](https://user-images.githubusercontent.com/7023022/73378880-9c805980-42c1-11ea-99e1-9fb31a4b33f6.PNG)

**Comment by bitshiftersgmbh** [comment]
Das ist natürlich von Projekt zu Projekt unterschiedlich (wie @tbaddade schon andeutete).
Es kann auch vorkommen dass das leer bleibt und ich mir an anderer Stelle (Template z.B.) dafür ganz eigene Dinger für <title> und META-Description aus mehreren DB-Feldern zusammenschreibe.

**Comment by iceman-fx** [comment]
OK, cool.
Sind die Felder standard? 
Und ersetzen die automatisch den Inhalt von title, desc, etc. Oder muss man dies dann händisch im Template abfragen?

**Comment by rkemmere** [comment]
Das ist von Projekt zu Projekt unterschiedlich. Manchmal baut man den Titel aus einem DB Feld, manchmal auch im Template.
Daher mein Vorschlag, wie auch bei SearchIt, über die URLs vom Frontend zu parsen. Denn diese stehen ja in der Sitemap drin.

**Comment by iceman-fx** [comment]
In der aktuellen Version ist nun auch ein CheckUp der URLs des URL-Addon v2 enthalten.
