### ISSUE TITLE
Wortgruppe anstatt eines einzelnen Keywords

### ISSUE THREAD

**Issue by georgkaser** [iceman-fx/seocheckup#9]
Ein cooles Feature wäre, wenn man nicht nur ein Focus Keyword festlegen könnte, sondern eine Kombination von 2 oder 3 Schlüsselwörtern, auf die man eine Seite optimiert.

**Comment by iceman-fx** [comment]
Ab Version 1.4.5 sind mehrere Keywords prüfbar
